name: terraform-deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-deploy
  cancel-in-progress: false

jobs:
  plan-dev:
    uses: ./.github/workflows/_infra_tf.yml
    with:
      environment: dev
      gh_environment: dev-preview
      command: plan

  apply-dev:
    needs: plan-dev
    uses: ./.github/workflows/_infra_tf.yml
    with:
      environment: dev
      gh_environment: dev
      command: apply

  post-deploy-dev:
    needs: apply-dev
    uses: ./.github/workflows/_post-deploy.yml
    with:
      environment: dev
      gh_environment: dev
      infra_flavor: terraform
      working_directory: infra_tf
      terraform_version: "1.9.x"